blank_issues_enabled: false
contact_links:
  - name: Do you want to discuss CIP ideas or ask questions about the process?
    url: https://forum.ceramic.network/c/discussion-about-ceramic-improvement-proposals/
    about: Use the Ceramic forum for CIP-related discussion!
